import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;

import java.time.LocalDate;

public class InputChecker {
    private TextField firstName;
    private TextField lastName;
    private DatePicker startDate;
    private DatePicker endDate;

    public InputChecker(TextField firstName, TextField lastName, DatePicker startDate, DatePicker endDate) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * Checks the input by checking the members of the class
     * @return returns the response that was generated by checking the input
     */
    public String checkInput() {
        String response = "";
        if(!isValidFirstName()) {
            response += firstNameErrorMessage();
        }
        if(!isValidLastName()) {
            response += lastNameErrorMessage();
        }
        if(!isValidStartDate()) {
            response += startDateErrorMessage();
        }
        if(!isValidEndDate()) {
            response += endDateErrorMessage();
        }
        if(!isSeqDate()) {
            response += seqDateErrorMessage();
        }
        return response;
    }

    /**
     * Returns true if there are no spaces & the name was not empty, otherwise will return false
     * @return a boolean that represents whether or not the firstName was valid
     */
    private boolean isValidFirstName() {
        String text = firstName.getText();
        return text.length() != 0 && !text.contains(" ");
    }

    /**
     * Returns true if the name is not empty, otherwise will return false
     * @return a boolean that represents whether or not a lastName was valid
     */
    private boolean isValidLastName() {
        String text = lastName.getText();
        return text.length() != 0;
    }

    /**
     * Returns true if the date is not empty, otherwise will return false
     * @return a boolean that represents whether or not a startDate was valid
     */
    private boolean isValidStartDate() {
        try {
            LocalDate localDate = startDate.getValue();
            String text = localDate.toString();
            return text.length() != 0;
        } catch (Exception exception) {
            return false;
        }
    }

    /**
     * Returns true if the date is not empty, otherwise will return false
     * @return a boolean that represents whether or not a endDate was valid
     */
    private boolean isValidEndDate() {
        try {
            LocalDate localDate = endDate.getValue();
            String text = localDate.toString();
            return text.length() != 0;
        } catch (Exception exception) {
            return false;
        }
    }

    /**
     * Checks to see if the endDate is after the firstDate
     * @return a boolean that returns whether or not the endDate is after the firstDate
     */
    private boolean isSeqDate() {
        try {
            return startDate.getValue().isBefore(endDate.getValue());
        } catch (Exception exception) {
            return false;
        }
    }

    private String firstNameErrorMessage() {
        return "Make sure to enter in a first name. \n" +
                "Also insure that the first name entered does not include any spaces. ";
    }

    private String lastNameErrorMessage() {
        return "Make sure to enter in a last name. \n" +
                "Also insure that the last name entered has no trailing spaces. \n" +
                "If there are any Jrs, III, etc., add that at the end of the last name. ";
    }

    private String startDateErrorMessage() {
        return "Make sure to enter a starting date. \n" +
                "The starting date should be in some form of a MM/DD/YYYY format, \n" +
                "with MANDATORY selection from the calendar option. \n" +
                "The program only recognizes the most recently calendar picked date ";
    }

    private String endDateErrorMessage() {
        return "Make sure to enter an ending date. \n" +
                "The ending date should be in some form of a MM/DD/YYYY format, \n" +
                "with MANDATORY selection from the calendar option. \n" +
                "The program only recognizes the most recently calendar picked date ";
    }

    private String seqDateErrorMessage() {
        return " Make sure to put two valid ordered dates. ";
    }
}
